### ISSUE TITLE
homeshick refresh mistakenly counts repos as fresh

### ISSUE THREAD

**Issue by PerilousApricot** [andsens/homeshick#101]
I tried to do a ```homeshick refresh``` on an old machine that I had just added a new castle "dotfiles_private" to but didn't add the origin. I got the following

```
homeshick refresh
     outdated dotfiles
     outdated dotfiles_private
     outdated homeshick
      refresh The castles dotfiles,dotfiles_private,homeshick are outdated.
        pull? [yN] y
         pull dotfiles
         pull dotfiles_private
        error Unable to pull /Users/meloam/.homesick/repos/dotfiles_private. Git says:
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
```

I didn't end up getting to pull homeshick, but the caching said it was okay:
```
homeshick refresh
        fresh dotfiles
        fresh dotfiles_private
        fresh homeshick
```

I assume that the "last updated" flag is updated before the pull successfully returns?

**Comment by andsens** [comment]
Fixed in dev and testing :-)

You can go ahead and try out the testing branch if you like. I'll let the changes simmer there for a while before merging into master.

**Comment by andsens** [comment]
Fixed :-)
