### ISSUE TITLE
I lost my castle

### ISSUE THREAD

**Issue by xr09** [andsens/homeshick#106]
Maybe I'm missing some obvious issue here but let me just tell my story:

I created a new castle:
    homeshick generate vim
I tracked my vim folder
    homeshick track vim .vim/
I made a mess, wanted to start over like before homeshick, my first instint was:
    rm -rfv ~/.homesick/repos/vim
Great... now all I got are null symlinks in ~/.vim folder.

Totally my bad I know, but maybe using hardlinks instead of symlinks, or a new "untrack" command could highlight the fact that the process of "untracking" unpushed castles is dangerous and should be done with extreme care.

Any thoughts on this?

**Comment by mrmachine** [comment]
What about a hard link option? Would that interfere with homesick's ability to recognise files that are not linked? In general, I think I'd prefer hard links because:

a) some and backup tools tools don't follow symlinks, they back them up.
b) accidentally tracking a symlink is annoying
