### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by justmytwospence** [andsens/homeshick#127]
I don't think one exists yet, but it would be a nice touch to simplify installation on OSX at least.

**Comment by andsens** [comment]
Guess I'm reopening this one :-)
Merging #138 made it possible to change the install dir of homeshick and there are already packages out there for both openSUSE and archlinux. If anybody would like to create a homebrew formula for homeshick, I'd be happy to help.

**Comment by benjaminfrank** [comment]
As I am using homeshick now, I opened a PR for homeshick homebrew/homebrew-core#1758

**Comment by benjaminfrank** [comment]
>     The patch is needed because due to the fact that bin/homeshick is not simply 
>     a binary you can execute. However, homebrew makes files in bin/ available in 
>     PATH leading to strange results before the required export and sourcing 
>     happens.
> 
> This doesn't sound particularly easy to package for Homebrew given the need for the not small patch that won't ever be accepted upstream in the current format. It seems like a good middle ground would be to work with upstream for better configurability.

Hey @andsens, ist there something that could be done to make packaging homeshick for homebrew easier? main issue is that files in /bin are treated as normal executables and thus added to $PATH. to prevent a situation where homeshick (the one in /bin) is available before the source'ing happens, I moved it out of the way for homebrew and adjusted the the scripts a user needs to source.

**Comment by andsens** [comment]
> to prevent a situation where homeshick (the one in /bin) is available before the source'ing happens, I moved it out of the way for homebrew and adjusted the the scripts a user needs to source.

You don't need to. In all languages aliases or functions take precedence over executables on `$PATH`.
I just tested it for bash, zsh and csh myself (not fish though, but I'd be surprised if it was different).

**Comment by benjaminfrank** [comment]
yes, however homeshick (as binary) is immediately available and creates a strange looking error:
```bash
XXPM00355799A:homebrew-core d061778$ homeshick
/usr/local/bin/homeshick: Zeile 6: /Users/d061778/.homesick/repos/homeshick/lib/exit_status.sh: No such file or directory
/usr/local/bin/homeshick: Zeile 7: /Users/d061778/.homesick/repos/homeshick/lib/fs.sh: No such file or directory
/usr/local/bin/homeshick: Zeile 8: /Users/d061778/.homesick/repos/homeshick/lib/git.sh: No such file or directory
/usr/local/bin/homeshick: Zeile 9: /Users/d061778/.homesick/repos/homeshick/lib/log.sh: No such file or directory
/usr/local/bin/homeshick: Zeile 10: /Users/d061778/.homesick/repos/homeshick/lib/prompt.sh: No such file or directory
/usr/local/bin/homeshick: Zeile 127: /Users/d061778/.homesick/repos/homeshick/lib/commands/help.sh: No such file or directory
GNU bash, Version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)
Die Shell Kommandos sind intern definiert.  Mit `help' kann eine Liste
angesehen werden.  Durch `help Name' wird eine Beschreibung der
Funktion `Name' angezeigt.  Die Dokumentation ist mit `info bash'
einsehbar.  Detaillierte Beschreibungen der Shellkommandos sind mit
`man -k' oder `info' abrufbar.

Ein Stern (*) neben dem Namen kennzeichnet deaktivierte Kommandos.

 Jobbezeichnung [&]                      history [-c] [-d Offset] [n] oder hi>
 (( Ausdruck ))                          if Kommandos; then Kommandos; [ elif>
 . Dateiname [Argumente]                 jobs [-lnprs] [Jobbez. ...] or jobs >
 :                                       kill [-s Signalname | -n Signalnumme>
 [ Argument... ]                         let Argument [Argument ...]
 [[ Ausdruck ]]                          local [Option] Name[=Wert] ...
 alias [-p] [Name[=Wert] ... ]           logout [n]
 bg [Jobbezeichnung ...]                 mapfile [-n Anzahl] [-O Quelle] [-s >
 bind [-lpsvPSVX] [-m Tastaturtabelle]>  popd [-n] [+N | -N]
 break [n]                               printf [-v var] Format [Argumente]
 builtin [Shellkommando [Argument ...]>  pushd [-n] [+N | -N | Verzeichnis]
 caller [Ausdruck]                       pwd [-LP]
 case Wort in [Muster [| Muster]...) K>  read [-ers] [-a Feld] [-d Begrenzer]>
 cd [-L|[-P [-e]] [-@]] [Verzeichnis]    readarray [-n Anzahl] [-O Quelle] [->
 command [-pVv] Kommando [Argument ...>  readonly [-aAf] [Name[=Wert] ...] od>
 compgen [-abcdefgjksuv] [-o Option]  >  return [n]
 complete [-abcdefgjksuv] [-pr] [-DE] >  select Name [in Wortliste ... ;] do >
 compopt [-o|+o Option] [-DE] [Name ..>  set [-abefhkmnptuvxBCHP] [-o Option]>
 continue [n]                            shift [n]
 coproc [Name] Kommando [Umleitungen]    shopt [-pqsu] [-o] [Optionsname ...]>
 declare [-aAfFgilrntux] [-p] Variable>  source Dateiname [Argumente]
 dirs [-clpv] [+N] [-N]                  suspend [-f]
 disown [-h] [-ar] [Jobbezeichnung ...>  test [Ausdruck]
 echo [-neE] [Argument ...]              time [-p] Pipeline
 enable [-a] [-dnps] [-f Dateiname] [N>  times
 eval [Argument ...]                     trap [-lp] [[Argument] Signalbezeich>
 exec [-cl] [-a Name] [Kommando [Argum>  true
 exit [n]                                type [-afptP] Name [Name ...]
 export [-fn] [Name[=Wert] ...] oder e>  typeset [-aAfFgilrtux] [-p] Name[=We>
 false                                   ulimit [-SHabcdefilmnpqrstuvxT] [Gre>
 fc [-e Editor] [-lnr] [Anfang] [Ende]>  umask [-p] [-S] [Modus]
 fg [Jobbezeichnung]                     unalias [-a] Name [Name ...]
 for Name [in Wortliste ... ] ; do Kom>  unset [-f] [-v] [-n] [NAME ...]
 for (( Ausdr1; Ausdr2; Ausdr3 )); do >  until Kommandos; do Kommandos; done
 function Name { Kommandos ; } oder Na>  variables - Namen und Bedeutung eini>
 getopts Optionen Variable [Argumente]>   wait [-n] [id ...]
 hash [-lr] [-p Pfadname] [-dt] [Name >  while Kommandos; do Kommandos; done
 help [-dms] [Muster ...]                { Kommandos ; }
```
While this is sort of expected (neither HOMESHICK_DIR was exported nor the relevant file sourced), I think we could avoid this kind of confusion easily.

**Comment by andsens** [comment]
Ah. OK, why then not simply patch [this line](https://github.com/andsens/homeshick/blob/e8d021c10c7a54fba0a81a7995ca0148c07f3a9b/bin/homeshick#L5). Doing that also ensures that the executable works. Meaning it's scriptable etc.

**Comment by benjaminfrank** [comment]
Wouldn't this mean `homeshick cd` would no longer work?
Currently I move & patch the source files for the different shells to keep the cd ability.

**Comment by andsens** [comment]
> Wouldn't this mean homeshick cd would no longer work?

Well no. As soon as you source the proper function file writing `homeshick` in bash refers to the function rather than the executable, so it just overrides.

You can do one of two things:
* Make sure that `$HOMESHICK_DIR` is set to the proper directory. This requires that users add that setting to their bashrc, which isn't really much to ask, since they need to add the source statement anyways (openSuse and archLinux do it this way I think).
* Change the `$HOMESHICK_DIR` default to `${opt_prefix}` in all the files. This would make sure that homeshick can be called without `$HOMESHICK_DIR` having to be set, which is better integration.

It's up to you really, I don't care either way. Still, keeping in line with other OSes seems like a good idea, not least because you can copypaste any fixes they make later on.

**Comment by benjaminfrank** [comment]
Ok, that sounds like a reasonable approach, as the patch would besome a simple one-liner. thanks for your help

**Comment by andsens** [comment]
Closing. Seems everything worked out great!

p.s.: https://github.com/andsens/homeshick/wiki/Installation#homebrew ;-)

**Comment by leoj3n** [comment]
:+1:
