### ISSUE TITLE
"shallow symlinking" not working

### ISSUE THREAD

**Issue by tomhoover** [andsens/homeshick#128]
I'm attempting to use *shallow symlinking* (as described at https://github.com/andsens/homeshick/wiki/Symlinking#shallow-symlinking), but have been unsuccessful. I've created a directory named **local** as a peer to **home** and created a symlink from **home/.local** to **../local**; however, executing *homeshick link* fails to create a **.local** symlink in $HOME.

The following is my dotfiles-castle directory structure (I've cleaned up the tree output by deleting the .git directory):

```
$ tree -a dotfiles-castle/

dotfiles-castle/
├── home
│   ├── .bash_profile
│   ├── .bashrc
│   ├── .local -> ../local
│   └── .profile
└── local
    └── Darwin.bash_profile
```

**Comment by andsens** [comment]
>  but have been unsuccessful

You'll have to be a little more specific :-)  
However, I *think* I know what your problem is: Remember to add the files to git, homeshickonly links files tracked by git - I totally forgot to mention that change in the docs, just gotta figure out where to do it.

Regardless, the following definitely works when using `test/interactive`:

    homeshick generate test
    homeshick cd test
    mkdir local
    touch local/Darwin.bash_profile
    ln -s ../local home/.local
    git add .
    git commit -m 'add .local'
    homeshick link test

**Comment by tomhoover** [comment]
That was it. I only installed homeshick today, and have been trying to decide whether to make it my dotfile manager of choice--since I hadn't yet decided, I hadn't bother committing anything to git. Thanks!

**Comment by andsens** [comment]
I'm glad I could help, and I hope you'll go with homeshick.

I've update the docs. The thing about only linking git-tracked files is now mentioned in [two](https://github.com/andsens/homeshick/wiki/Commands/_compare/f1cf19d1f16dcf87bba66abc93160a688ca2870d...37b5618a8d0a8c4c1844fc56f530a63ad092fe41) separate [places](https://github.com/andsens/homeshick/wiki/Symlinking/_compare/cf05d1c173dbed06d4d82ea1edc2b8e833196568...37b5618a8d0a8c4c1844fc56f530a63ad092fe41), I hope that prevents any confusion in the future.
