### ISSUE TITLE
homeshick completion broken on symlinked castles

### ISSUE THREAD

**Issue by darkfeline** [andsens/homeshick#140]
Trying to complete by pressing TAB after

    $ homeshick track

doesn't complete properly if the castle is symlinked into `.homesick/repos`

**Comment by andsens** [comment]
Ah, you're right. [Here's the problem](https://github.com/andsens/homeshick/blob/611dcf04507841115f6d1ec0680282701bb5b697/completions/homeshick-completion.bash#L43). I'll see if I find the time to fix this today.

**Comment by jjlin** [comment]
I think the fix is as simple as just making it `find -L`. I can open a PR for this.

**Comment by darkfeline** [comment]
Confirmed fixed, thanks.
