### ISSUE TITLE
How to change file permission after cloning dotfiles

### ISSUE THREAD

**Issue by QiangF** [andsens/homeshick#146]
Hi Everyone,
I want to manage all my customised configuration files in the whole system. One example is /etc/apt/sources.list. Is there a way to set the right permission for these files like etckeeper? 
Thank you!

**Comment by andsens** [comment]
Directly using homeshick: no. This is beyond the scope of homeshick I'm afraid.
You could however run homeshick pull/link with `sudo` and use `umask` to get homeshick to create/symlink with the right permissions. [Consult the wiki](https://github.com/andsens/homeshick/wiki/Symlinking#files-outside-your-home-directory) to see how you can symlink files outside your `home/` dir.

**Comment by QiangF** [comment]
For the record, here is my wishlist.
https://github.com/anishathalye/dotbot/issues/49
Thank you!

**Comment by binarykitchen** [comment]
@andsens can you expand more on that, how to use `umask` for correcting file permissions?
