### ISSUE TITLE
Add ability to download shallow clones when doing homeshick clone.

### ISSUE THREAD

**Issue by absorber** [andsens/homeshick#153]
When I do `homeshick clone`, I would like to specify git clone's `--depth` option as to not download the entire git revision history.

If I'm not mistaken, the https://github.com/andsens/homeshick/blob/master/lib/commands/clone.sh should be edited, so when I have time I can submit a PR where you can witness my horrible Bash skills.

**Comment by andsens** [comment]
While there may be a valid use-case for this, you have to keep in mind that we could also come up with use-cases for the remaining 21 switches of `git clone` (and arguments, see #155):
```
git clone [--template=<template_directory>]
          [-l] [-s] [--no-hardlinks] [-q] [-n] [--bare] [--mirror]
          [-o <name>] [-b <name>] [-u <upload-pack>] [--reference <repository>]
          [--dissociate] [--separate-git-dir <git dir>]
          [--depth <depth>] [--[no-]single-branch]
          [--recursive | --recurse-submodules] [--[no-]shallow-submodules]
          [--jobs <n>] [--] <repository> [<directory>]
```

Where should we stop?  
Regardless, I built homeshick to be highly hackable and easy to keep up-to-date with an upstream, so I encourage you to make the modifications and just run your own fork ([lots of others do this](https://github.com/andsens/homeshick/network/members) :-)).

Closing as won't fix.
