### ISSUE TITLE
Inconsistency between brew install instructions and installation page

### ISSUE THREAD

**Issue by ChristopherA** [andsens/homeshick#158]
`brew install homeshick` reports

~~~
To enable the `homeshick cd <CASTLE>` command, you need to
`export HOMESHICK_DIR=/usr/local/opt/homeshick`
and
`source "/usr/local/opt/homeshick/homeshick.sh"`
in your $HOME/.bash_rc
~~~

However, the installation instructions at https://github.com/andsens/homeshick/wiki/Installation have a statement that printf's it into `.bashrc`

Two problems: the inconsistency, and which is the preferred place?

If you are bootstrapping from a brand new installation (i.e. a new macOS Sierra install) the bootstrapping tutorial at https://github.com/andsens/homeshick/wiki/Tutorials has similar inconsistency problems.

**Comment by andsens** [comment]
The difference is that homebrew installs homeshick to a non-default location (i.e. `/usr/local/opt/homeshick`), while the instructions in both the wiki and the readme are for a default install where `HOMESHICK_DIR` does not need to be set. The `printf` is just a copy & paste convenience.

However, the instruction about `.bash_rc` with an underscore in the homebrew formula is wrong, there is no underscore in `.bashrc` - you should probably open an issue on the homebrew repo for this.

**Comment by ChristopherA** [comment]
This pull request was accepted.

**Comment by andsens** [comment]
Nice, thank you :-)
