### ISSUE TITLE
"homeshick check" fails using git 1.7.1 

### ISSUE THREAD

**Issue by wlonkly** [andsens/homeshick#160]
Noticed that the `git ls-remote` call in `homeshick check` passes the `-q` option which only appeared in git 1.8, which means check doesn't work in CentOS 6/RHEL 6 which ships with that git version.

Calling `git ls-remote` with an explicit repo and ref doesn't output a URL line, so it's safe to omit the `-q`. PR incoming.

**Comment by andsens** [comment]
Fixed.
