### ISSUE TITLE
skip broken submodules

### ISSUE THREAD

**Issue by shadowbq** [andsens/homeshick#161]
There should be a flag to skip broken submodules / submodules that "fatal: No url found for submodule path XXXXXXXX" 

This would be helpful as when I install castles, I don't always want to fetch the git submodules. (cascading vim dependencies etc..)

**Comment by andsens** [comment]
Why not just convert those submodules into castles and symlink them from your dotfiles? Then you can selectively update them when you want to, that's what I did with all my vim plugins.

**Comment by shadowbq** [comment]
That would work. 

This was more a comment as when you `git clone` the behavior is different (doesnt halt on submodule issues)  than `homesick clone` if there is a sub-module downstream problem. You have to destroy the castle, as it only partially checked out and escaped, check out your castle via git somewhere else. fix it. push it. reclone the castle.

**Comment by andsens** [comment]
huh, that's weird. [Check out the code](https://github.com/andsens/homeshick/blob/23cb8a7ed3fb654eb502313c3ba1c26bf4d730b2/lib/commands/clone.sh#L22), all homeshick does is a `git clone --recursive` on `clone` and a `git pull` + `git submodule update --recursive --init` on `pull`. I don't see a lot of wiggleroom behaviourally in those two commands to diverge from git.

**Comment by shadowbq** [comment]
I was commenting on being able to do a non-recursive pull thats all. You can close it.
