### ISSUE TITLE
How do you source the actual symlinked files?

### ISSUE THREAD

**Issue by entheologist** [andsens/homeshick#162]
I symlinked all the files in my castle, but none of them are being loaded into bash. Is there an extra function I need to add to source all of the files?

**Comment by andsens** [comment]
If your files are being properly symlinked, we are departing from the realm

**Comment by andsens** [comment]
> Is there an extra function I need to add to source all of the files?

There is not. If your files are being properly symlinked, we are departing from the realm of "problems with homeshick" and entering "problems with bash", which this issue tracker is not really intended for. Nevertheless, here are some tips:

* Doublecheck the filename and make sure it's called `.bashrc` ([check the docs](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html) for special  filenames)
* Check if the file is readable, simply `cat ~/.bashrc` and check if you get the output you expect.
* Maybe you have an early exit/return somewhere, you can debug your scripts by running `set -x` at the very beginning of your file to see what happens during execution

Those are the basics, I hope it helps! Closing as not relevant (if you find out that this is indeed a problem with homeshick, feel free to reopen it).
