### ISSUE TITLE
homeshick --clone --batch produces blank line

### ISSUE THREAD

**Issue by kruton** [andsens/homeshick#167]
It appears that 69095a4649ecfe091e2a7dcbfdb512384b614024 introduced a regression in `homeshick --clone --batch` such that it all always produces a blank line.

**Comment by kruton** [comment]
Perhaps this could  be amended to be:
```bash
[[ $@ ]] && printf '%s\n' "$@"
```

**Comment by andsens** [comment]
oh yeah, good catch, thanks :-)

**Comment by andsens** [comment]
Fixed.
