### ISSUE TITLE
Command 'string' not found... homeshick.fish

### ISSUE THREAD

**Issue by Smok07** [andsens/homeshick#176]
Hello! Today I'm trying to create my first CASTLE, but I'm getting this message
```
Command 'string' not found...
in command substitution
	called on line 5 of file ~/.homesick/repos/homeshick/homeshick.fish

```
The 5 line contains:
`eval $HOMESHICK_DIR/bin/homeshick (string escape -- $argv)`

Does this mean that I need to install some tools or packages?

Thanks!

ps: I can create CASTLE from bash, but not from fish

**Comment by psliwka** [comment]
`string` is fish's builtin: https://fishshell.com/docs/current/commands.html#string

**Comment by andsens** [comment]
This... seems weird. Are you sure you're in the right shell when invoking? I honestly don't know enough about fish to comment, so I'd very much like someone to chime in with a diagnosis. @herrbischoff maybe?

**Comment by Smok07** [comment]
Thanks guys, I thought I needed to install something like string-tools, but I found that I need to **update the fish to the latest version**
my fish is:
_fish, version 2.2.0_

and to update, I needed to add a repository, here is instructions:
https://launchpad.net/~fish-shell/+archive/ubuntu/release-2

I spent a few days searching for "string"
thanks for help %)

**Comment by herrbischoff** [comment]
Good to see you were successful in troubleshooting this yourself. Indeed, everything below fish v2.5 will likely behave/break in unexpected ways. There have been major updates over time.
