### ISSUE TITLE
Clone command should use git@github as the remote origin

### ISSUE THREAD

**Issue by binarykitchen** [andsens/homeshick#189]
Currently it creates something like

```
remote.origin.url=https://github.com/abc/dotfiles.git
```

when cloned using `$HOME/.homesick/repos/homeshick/bin/homeshick clone abc/dotfiles`

which forces me to enter github username and password every time. Don't want to. Already have my ssh keys there.

Meaning I ll have to manually modify the auto generated git config file to

```
remote.origin.url=git@github.abc/dotfiles.git
```

A bit painful to do so on every machine. Can't this be a parameter of the clone command?

**Comment by haraldkoch** [comment]
Do you have your dotfiles in a private repo?

In my experience with public repos, the opposite is true; when cloning or pulling, I only get prompted for a username/password if I use the SSH URL.

**Comment by andsens** [comment]
The github *shorthand* is meant for cloning public repos, like e.g. `robbyrussell/oh-my-zsh` where you don't need push access. If you need to clone a private repo use `homeshick clone git@github.com....`

**Comment by binarykitchen** [comment]
@haraldkoch yes my dotfiles are in a private repo

do you think you can add this to the readme that the `homeshick clone git@github.com....` syntax is possible too for private repos?

**Comment by andsens** [comment]
[Done](https://github.com/andsens/homeshick/wiki/Commands/_compare/37b5618a8d0a8c4c1844fc56f530a63ad092fe41...1460e75a4f1794a012e4a17610f4c4f1c0bf0fe3).
