### ISSUE TITLE
Cloning takes forever for simple repos

### ISSUE THREAD

**Issue by Abhijay** [andsens/homeshick#191]
I have a castle that only just contains my .vimrc, but when I `homeshick clone` it takes upwards of 5 minutes to complete the command. As this should basically amount to a `git clone` and a symlink, I can't understand what takes so long? Both of those commands run virtually instantaneously on my machine.

**Comment by andsens** [comment]
That does indeed sound weird. Try running the clone command using this:
```
bash -x ~/.homesick/repos/homeshick/bin/homeshick clone git@github.com:Abhijay/REPONAME
```

That should output every command homeshick runs (excluding the ones run by subshells). You won't get any timing information, but you should be able to see which command hangs.
