### ISSUE TITLE
解决zsh补全msfvenom出现_values:compvalues:11: not enough arguments(参数不足)的问题

### ISSUE THREAD

**Issue by fengziHK** [andsens/homeshick#195]
@#fengzi 2020309

#解决zsh补全msfvenom出现_values:compvalues:11: not enough arguments(参数不足)的问题

#1、venom-cache ( msfvenom --list payloads to list )文件放入~.zsh\

#2、~/.zshrc配置文件

#插件加入

#plugins=(git msfvenom)

#最后加入

#fpath=(~/.zsh/completion $fpath)

#autoload -Uz compinit && compinit -i

**Comment by andsens** [comment]
我认为您已将发布到错误的存储库
这不应该在https://github.com/Green-m/msfvenom-zsh-completion中吗？

**Comment by fengziHK** [comment]
ye。。
