### ISSUE TITLE
Clone to directory, and set working directory, like git -C directory

### ISSUE THREAD

**Issue by shadowrylander** [andsens/homeshick#198]
Hello!

I'd like to know if there is any way clone a castle to a specific directory, and work in that directory similar to how `git -C directory` works; the reason for asking is that I'd like to add this to a python program I'm working on, incorporating the `yadm` program as well, which also has the ability to specify which directory to clone to and work in.

In addition, would you happen to know if any possible solutions would work with the Ruby `homesick` version as well?

Thank you kindly for the help!

**Comment by andsens** [comment]
I don't know about `homesick`, but `homeshick` completely relies on `$HOME`. Meaning if you invoke it with `HOME=/some/other/dir`, it will assumes that is your home directory and work as expected. There is no way to get rid of the `$HOME/.homesick/repos` suffix though, that part is hardcoded.

**Comment by shadowrylander** [comment]
Ah, that makes makes sense; thanks!
