### ISSUE TITLE
Installing homeschick broke the terminal

### ISSUE THREAD

**Issue by davidhaley** [andsens/homeshick#210]
I followed the setup instructions (clone the repository, add the path to the script to my .bashrc file, and then sourced .bashrc), and now my terminal is completely broken. The moment it opens, it closes. Even logging into the shell via a separate TTY (using ctrl+alt+f6) doesn't work. Restarting my system didn't work.

Ubuntu 21.10

**Comment by davidhaley** [comment]
I opened .bashrc and removed the line that sources the homeschick script and the issue is gone.

**Comment by andsens** [comment]
Without knowing what your .bashrc looked like when things where crashing, I have no way of helping you. Feel free to reopen with the contents of your .bashrc
