### ISSUE TITLE
File names with % cause problems with printf

### ISSUE THREAD

**Issue by ncallister** [andsens/homeshick#223]
There are some applications which create files with % characters in them such as `.config/kate/externaltools/Insert\%20UUID.ini`. Unfortunately printf interprets the % character as an escape character and so the `homeshick link` command fails with the message: `.homesick/repos/homeshick/lib/commands/link.sh: line 108: printf: `U': invalid format character`.

**Comment by andsens** [comment]
Good catch Nathan! [I have pushed a bug fix](https://github.com/andsens/homeshick/commit/e46584202dc7b889b52d2458377f62c8570faad0) that is a little more robust than your PR, where `$path` is instead passed as an arg to `printf`. I figured out what initially caused the issue with `printf "%s\0" "$path"` not working: `git ls-files` escapes special chars, which makes a lot of sense, but that means we need to re-interpret the escaped chars with `printf`. By telling git to nulbyte delimit the paths we avoid that whole escaping/re-interpreting and can just pass them along verbatim.

**Comment by andsens** [comment]
p.s.: The changes are now available in the testing branch, so go ahead and switch to that if you want to run it right away :-)

**Comment by ncallister** [comment]
`homeshick link` is now working with all files using the `testing` branch. Thank you :grinning:

**Comment by andsens** [comment]
Merged to `master`

**Comment by ushkinaz** [comment]
@andsens this change breaks homeshick on MacOS, where sed does not have '-z'

> » homeshick link   ↵ 
sed: illegal option -- z
usage: sed script [-EHalnru] [-i extension] [file ...]
	sed [-EHalnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
fatal: run_command returned non-zero status for home/.oh-my-zsh

**Comment by andsens** [comment]
Ah damn. Don't have a mac to test this on any longer. I should find a way to run the tests using `bsdutils` or something.  
Could you verify that it works when you replace this line: https://github.com/andsens/homeshick/blob/9768486e513523b1a3f7d3e44954e65eb2f6b979/lib/submodule_files.sh#L20
with `git ls-files -z | sed "s#\x00#\x00${repo//#/\\#}/#"`?

I have opened a new issue: #228  
Please report back there.
