### ISSUE TITLE
Make `--force` work with `homeshick clone`

### ISSUE THREAD

**Issue by jrhorn424** [andsens/homeshick#49]
Use case: Automated installs (should be idempotent, right?)

Expected: `homeshick clone user/repo --force` should not return non-zero exit when files exist. Why?

```
 Runtime options:
    ...
   -f, [--force]    # Overwrite files that already exist
```

Actual:

```
> $HOME/.homesick/repos/homeshick/bin/homeshick clone jrhorn424/dotfiles --batch --force
        clone https://github.com/jrhorn424/dotfiles.git
        error /home/deploy/.homesick/repos/dotfiles already exists
```

Same probably goes for `--skip`, in retrospect.

**Comment by g0t4** [comment]
Aside from dealing with an already existing repository, clone could also work with --force to add symlinks when in --batch mode. I might be missing something but it seems that --batch defaults to NO for symlinks. And --force can't override this to YES

**Comment by andsens** [comment]
> Aside from dealing with an already existing repository, clone could also work with --force to add symlinks when in --batch mode. I might be missing something but it seems that --batch defaults to NO for symlinks. And --force can't override this to YES

That is easy to work around actually, just run `homeshick --batch clone [repo]  && homeshick link -f [castle]`

**Comment by g0t4** [comment]
Yeah that works, I was just confused since clone prompts to symlink but
doesn’t accept —force.
