### ISSUE TITLE
zsh completion is not working

### ISSUE THREAD

**Issue by waiting-for-dev** [andsens/homeshick#89]
I followed [zsh completion instructions detailed in the wiki](https://github.com/andsens/homeshick/wiki/Installation#zsh-completion) but it doesn't work at all...

Am I missing something?

EDIT by @andsens: Since this issue seems to be visited a lot, [here's the solution](https://github.com/andsens/homeshick/issues/89#issuecomment-41508188) (for this specific case, that is. If something else works for you, feel free to add a comment to the issue)

**Comment by niklasnolte** [comment]
had the same problem on Linux 4.15.15-1-ARCH x86_64 GNU/Linux.
Reinstalling zsh (pacman) without any change to .zshrc fixed the issue.
