### ISSUE TITLE
Symlinks under Cygwin

### ISSUE THREAD

**Issue by ngaloppo** [andsens/homeshick#99]
What is the preferred way of using homeshick under windows? I find that when I run homeshick under Cygwin, it creates "cygwin" symlinks, which breaks terribly for non-Cygwin aware tools (e.g. Native Gvim). 

I heard that there might be a (trick)[http://stackoverflow.com/questions/18654162/enable-ntfs-symbolic-links-for-cygwin] to force Cygwin to use native NTFS links, but I haven't been able to make that work. 

I'll take any suggestions :)

**Comment by gdw2** [comment]
I just wanted to report that it homeschick seems to be working fairly well for me on Cygwin-on-Win7 using `CYGWIN=winsymlinks:lnk` which _doesn't_ require admin privileges.  The only windows program that I'm dealing with that needs to traverse the links is gvim.

**Comment by andsens** [comment]
Nice :-)
Maybe you could add a note to the [FAQ](https://github.com/andsens/homeshick/wiki/FAQ)?
